### PR TITLE
Initial Client Integration

### PR DESCRIPTION
**Pull request by mlavin**
Adds Backbone and dependencies. Login page with adds token on the client.

### CODE REVIEW

**Comment by mlavin** [comment]
On second thought maybe using the token auth isn't a good approach here and we should just stick to the session based auth...Not very RESTful but might be easier. Thoughts @daaray ?

**Comment by mlavin** [comment]
On second thought we are going to have to maintain that client state anyway. We can't rely on the server to track that when in offline mode.

**Comment by mlavin** [comment]
Added tests/CI config for good measure.

**Comment by daaray** [comment]
:cactus: :cactus: :cactus: :cactus: :cactus:

**Pull request merged**
